theme: jekyll-theme-hacker
# remote_theme: daviddarnes/alembic

# Site configuration
# 1. Files excluded from Jekyll builds
# 2. Installed Gems
# 3. Gem settings
# 4. Jekyll settings
# 5. Collections
# 6. Jekyll collections settings
# 7. Site settings
# 8. Site favicons & manifest icons
# 9. Site navigation

# 1. Files excluded from Jekyll builds
exclude:
- README.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- screenshot.png
- LICENSE
- CNAME
- Gemfile
- Gemfile.lock
- alembic-jekyll-theme.gemspec
- .jekyll-cache
- test.html

# 2. Installed Gems
plugins:
- jekyll-redirect-from
- jemoji

# 4. Jekyll settings
sass:
  style: compressed # Style compression
permalink: pretty  # Permalink style (/YYYY/MM/DD/page-name/)
excerpt_separator: <!-- more --> # Marks end of excerpt in posts
timezone: Europe/Madrid # Timezone for blog posts and alike

# 7. Site settings
encoding: utf-8 # Make sure the encoding is right
lang: es-CA # Set the site language
title: "Hack Just Desvern" # Site name or title, also used in jekyll-seo-tag
logo: "/assets/logos/logo.png" # Site logo, also used in jekyll-seo-tag
description: "Comunitat arrelada a Sant Just Desvern dedicada a promoure la cultura hacker." # Site description and default description, also used in jekyll-seo-tag
url: "hackjustdesvern.github.io" # Site url, also used in jekyll-seo-tag
baseurl: ""
repo: "https://github.com/hackjustdesvern/hackjustdesvern.github.io"
email: "hackjustdesvern@protonmail.com"
css_inline: true # Will insert all styles into a single <style> block in the <head> element and remove the style <link> reference
